services:
    db:
        container_name: db
        image: postgres:16
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '${DB_PORT:-5432}:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - organic_certification_network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
            interval: 10s
            timeout: 5s
            retries: 5

    test-db:
        container_name: test-db
        image: postgres:16
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}_test
        ports:
            - '5433:5432'
        volumes:
            - test_postgres_data:/var/lib/postgresql/data
        networks:
            - organic_certification_network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}_test']
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
    test_postgres_data:

networks:
    organic_certification_network:
        driver: bridge
